#!/usr/bin/env bash
# Installs Nginx with the following configurations:

sudo apt update
sudo apt install nginx -y
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo nginx -s reload
sudo echo "<html><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html
echo "Nginx configured to listen on port 80 and serving 'Hello World!' at /"
