#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
line="\\\trewrite ^/redirect_me http://pronic.tech permanent;"
sudo sed -i "26i $line" /etc/nginx/sites-available/default
sudo service nginx restart
